/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IUpdaterManager } from "../IUpdaterManager";

export class IUpdaterManager__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUpdaterManager {
    return new Contract(address, _abi, signerOrProvider) as IUpdaterManager;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_reporter",
        type: "address",
      },
    ],
    name: "slashUpdater",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "updater",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
